### ISSUE TITLE
CR unblocker no longer unblocks?

### ISSUE THREAD

**Issue by Atemu** [Onestay/CR-Unblocker-Server#5]
(Posting here because the addon repo is still down)

Since a few days ago the CR reloads, the language switches to English and there's a US flag in the footer instead of a German one, just like CR unblocker normally would, but I can't watch any of the region locked shows.

Example of a show that's not available in Germany:  

https://www.crunchyroll.com/goblin-slayer

>Sorry, due to licensing limitations, videos are unavailable in your region.

I've tried it in FF 64.0.2 on Android an Windows.

Is anyone able to reproduce this behavior?

**Comment by Oujiii** [comment]
Yes, I was able to reproduce it. 
As @onestay explained before, the extension works by getting a sess_id cookie from the US and injecting in your browser, making CR think you are actually in the US.  
If you manually get a US sess_id and inject in your browser, it would usually work, but right now, it only shows the US flags, but you can't actually see any of the episodes.
Using a VPN works, though.

Maybe CR changed the way they verify where you're connecting from, now they probably look at your IP address at all times.

**Comment by onestay** [comment]
Yeah, pretty sure they changed the way on how to detect region. It tried with a VPN and it works so I'm pretty sure they switched to IP based region checking.

**Comment by Oujiii** [comment]
Someone tested and it seems that they actually just changed the pages to not show the episode list if you don't have an US IP address. You can check it out [here](https://www.reddit.com/r/Crunchyroll/comments/9p087u/crunblocker_stopped_working/eepuyio/)

> It's strange but both of CR-unblocker and /u/Oujii's tutorial actually can still be used for watching, but you have to access the video directly. For example, when I tried to open the show page of That Time I Got Reincarnated as a Slime, it said that it couldn't be watched from my country. But when I tried to open the video directly through this link (episode 16), I could watch it just fine.

> Another strange thing is, the front page is still showing the shows that should be restricted by region and only available in the US. But only the front page. The simulcast list (for example) only shows the shows that are available in my country. I tried to uninstall my CR-unblocker, deleting my cookies, and install it again (also doing /u/Oujii's tutorial) but the result is still the same.

> So for now, I think it's stopping us from seeing the shows list, which has already been a hassle actually.

**Comment by Oujiii** [comment]
Just an update as the extension is currently working again.

**Comment by mirh** [comment]
I wonder if the outage(s?) they have been having in the last couple of days couldn't be related. 
.. Anyway, I can also confirm it works flawlessly.
