### ISSUE TITLE
In the browser plug-in, allow choosing where Open Crunchyroll points to

### ISSUE THREAD

**Issue by rimas-kudelis** [Onestay/CR-Unblocker-Server#6]
Assuming #5 can be fixed and the plugin doesn't lose it's purpose, it would be nice if a setting could be added to the plugin, which would allow me to choose which exactly CR page I want opened upon clicking Open Crunchyroll.

In my case, I always want to go to my queue instead of the front page, although its possible that some users will want to go straight to some show or elsewhere.

**Comment by ADarkHero** [comment]
Hi,
you could fix this issue yourself, if you edit a little file in the extensions settings.

1. Open the folder of the extension. In my case it's at the following path:
`C:\Users\adarkhero\AppData\Local\Google\Chrome\User Data\Profile 1\Extensions\agapeeilkibacbfeijlidlgppmjaaijn\2.2.2_0`

2. Open the file `popup.js` with a text editor

3. On line 23, replace `http://crunchyroll.com/videos/anime/` with `https://www.crunchyroll.com/home/queue/`

The next time, you click on the button, you should be redirected to your queue page. Just tried it myself, it seems to work fine.

**Comment by rimas-kudelis** [comment]
Thanks for this, but I think it'd be nicer to have this from upstream :)
Unless you don't plan to develop the extension anymore...

**Comment by onestay** [comment]
The problem I have with that is that I have no way to update all users. The extension repo is down and it's taken down from the chrome webstore. Sure I could implement it and upload it somewhere but I wouldn't know who has the version then which would make debugging and support extremely difficult with everybody being on a different version. Furthermore is my time at the moment fairly limited.

**Comment by rimas-kudelis** [comment]
Oh, I'm actually a Firefox user, and luckily the extension is still there on addons.m.o.

**Comment by onestay** [comment]
I personally have nothing to do with the distribution on the firefox store

**Comment by rimas-kudelis** [comment]
Oh, i see. OK then. :)

**Comment by mirh** [comment]
> The extension repo is down 

And.. didn't you like try to tell github there was an error?

**Comment by onestay** [comment]
GitHub can take repos on request down which circumvent access restrictions to restricted content, which my extension did

**Comment by mirh** [comment]
The DMCA notice just mentioned phony "copyrighted proprietary source code".
