### ISSUE TITLE
Addon does not seem to be working anymore.

### ISSUE THREAD

**Issue by Lucavon** [Onestay/CR-Unblocker-Server#9]
Heya!
Just 2 hours ago, the first post on the crunchyroll subreddit popped up, according to some other user, NordVPN doesn't work anymore. I tried to see if the CR unblocker still works, but I only get "CR-Unblocker couldn't get a session id".
Some other person in the comments on the reddit thread said this, too, but their comment was removed.

It seems they have cracked down on unblocking services once more.

Will it be possible to fix this?

**Comment by onestay** [comment]
I'm very limited time wise at the moment since I have tons of exams so I can't really work on this right now. If there's anybody who could submit a PR I'd merge it and update the server side code.

**Comment by onestay** [comment]
Extension should work again

**Comment by onestay** [comment]
Looks like it's broken again

**Comment by onestay** [comment]
Hmm I really have no idea what's going on. From what I can see in the logs there are some requests that work and some that don't.

**Comment by Lucavon** [comment]
Perhaps only some of their servers are denying requests, while others let them through?

**Comment by onestay** [comment]
I'll keep an eye on it. Right now it seems to work again.

**Comment by Lucavon** [comment]
Closing for now, as it seems to work perfectly again (been working for a few days).
